services:
  frontend:
    build: ./mern/frontend
    ports:
      - 5173:5173
    networks:
      - mern-network
    environment:
      REACT_APP_API_URL: http://backend:5050=value
  backend:
    build: ./mern/backend
    ports:
      - 5050:5050
    networks:
      - mern-network
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase 
    depends_on: 
      - mongodb
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - mern-network
    volumes:
      - mongo-data:/data/db 
networks:
  mern-network:
    driver: bridge 

volumes:
  mongo-data:
    driver: local