name: CI/CD Pipeline # This script builds image ,push image and run using docker-compose

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./Client # Directory where your frontend dockerfile is located
        push: true
        tags: (Dockerhub_username)/(image_name)
        
    - name: Build and push Backend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./Server # Directory where your backend dockerfile is located
        push: true
        tags: (Dockerhub_username)/(image_name)

    - name: Deploy application
      run: |
          echo "Deploying using docker-compose"
          docker-compose up -d
        