name: CI/CD Pipeline # This script builds image ,push image and run using docker-compose

on:
  push:
    branches:
    - sandip
jobs:
  build:
    runs-on: ubuntu-latest
  #step 1: Checkout code
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  #step 2: Setup Tailscale
    - name: Tailscale
      uses: tailscale/github-action@v3
      with:
        oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
        oauth-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
        tags: tag:ci
      # Setup SSH to the server
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace
  #Step 2: Run SonarQube Analysis
    - name: Run SonarQube Analysis
      run: |
        sonar-scanner \
          -Dsonar.projectKey=sonarmern \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://192.168.1.79:9000 \
          -Dsonar.login=sqp_1d6ded5b07b6a8cad3b2fbe35c24028c74078571

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./mern/frontend # Directory where your frontend dockerfile is located
        push: true
        tags: sandip1991/mern-docker-compose-frontend:latest
        
    - name: Build and push Backend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./mern/backend # Directory where your backend dockerfile is located
        push: true
        tags: sandip1991/mern-docker-compose-backend:latest
    # - name: Install Docker Compose
    #   run: |
    #     sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -Po '(?<=tag_name": "v)[^"]*')" \
    #     -o /usr/local/bin/docker-compose
    #     sudo chmod +x /usr/local/bin/docker-compose
    # - name: Deploy application
    #   run: |
    #       echo "Deploying using docker-compose"
    #       docker compose up -d
        