name: CI/CD Pipeline # This script builds image ,push image and run using docker-compose

on:
  push:
    branches:
      - sandip
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
  # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

  #step 2: Setup Tailscale
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: kGxaMAed5221CNTRL
          oauth-secret: tskey-client-kGxaMAed5221CNTRL-8bxVctdYk1FnFEK53U7w1FfVFY2r3YsDW
          tags: tag:ci
 # step 3: Setup SSH to the server
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          if_key_exists: replace
  #Step 4: Run SonarQube Analysis
      - name: Run SonarQube Analysis
        run: |
          git pull origin sandip 
          git checkout sandip
          sonar-scanner \
            -Dsonar.projectKey=sonarmern \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://192.168.1.79:9000 \
            -Dsonar.login=sqp_1d6ded5b07b6a8cad3b2fbe35c24028c74078571

    
        